import React from "react";
import About from "../_components/Apout/about";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <About />
    </div>
  );
};

export default AboutPage;
