import React from "react";
import Login from "../_components/Login/Login";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return (
    <div>
      <Login />
    </div>
  );
};

export default LoginPage;
