import React from "react";
import { Metadata } from "next";
import Contact from "../_components/Contact/Contact";

export const metadata: Metadata = {
  title: "Contact page",
  description: "Generated by create next app",
};
const ContactPage = () => {
  return (
    <div>
      <Contact />

    </div>
  );
};

export default ContactPage;
