// import SizeProvider from "@/context/SizeContext";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "meny",
  description: "Generated by create next app",
};

export default function MenuLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return {children};
}
