import React from "react";
import { prisma } from "@/lib/prisma";
import { ProductType } from "@/utils/productsType";
import { Metadata } from "next";
import MenuPart from "../_components/MenuPart/MenuPart";

export const metadata: Metadata = {
  title: "menu page",
  description: "Generated by create next app",
};
interface Category {
  id: string;
  name: string;
  description: string;
  order: number;
  products: ProductType[];
}


const MenuPage = async () => {
  const data: Category[] = await prisma.category.findMany({
    select: {
      id: true,
      name: true,
      order: true,
      description: true,
      products: {
        include: {
          sizes: { include: { product: true } },
          extras: { include: { product: true } },
        },
      },
    },
  });

  return (
    <>
      <div className="dark:bg-gray-900">
        <h1 className="text-2xl font-bold text-center p-7">Menu Page</h1>
        <p className="text-center mt-4">
          This is the menu page where you can explore our delicious offerings.
        </p>

        {data.map((item, index) => {
          {
            /* Additional content can be added here */
          }
          return (
            <MenuPart
              key={index}
              data={item.products}
              title={item.name}
              description={item.description ?? "no description"}
            />
          );
        })}
      </div>
    </>
  );
};

export default MenuPage;
