import React from "react";
import { Metadata } from "next";
import CartInput from "../_components/Cart/CartInput";

export const metadata: Metadata = {
  title: "Cart page",
  description: "Generated by create next app",
};

const CartPage = () => {
  return (
    <div>
      <div>
        <section>
          <CartInput />
        </section>
      </div>
    </div>
  );
};

export default CartPage;
