import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import './globals.css';
// import "./globals.css";
import Header from "./_components/header/header";
import { ThemeProvider } from "@/components/theme-provider";
import Fotter from "./_components/footer/Fotter";



const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Pizza Shop",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Header/>
          {children}
          <Fotter/>
        </ThemeProvider>
      </body>
    </html>
  );
}