// app/layout.tsx
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/header";
import { ThemeProvider } from "@/components/theme-provider";
import Fotter from "./_components/footer/Fotter";
import { Metadata } from "next";
import CartProviderWrapper from "./CartProviderWrapper";

export const metadata: Metadata = {
  title: "Pizza shop",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <CartProviderWrapper>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            {children}
            <Fotter />
          </ThemeProvider>
        </CartProviderWrapper>
      </body>
    </html>
  );
}