import React from "react";
import { Metadata } from "next";
import Register from "../_components/register/Register";

export const metadata: Metadata = {
  title: "Rigester page",
  description: "Generated by create next app",
};

const RegisterPage = () => {
  return (
    <div>
      <Register />
    </div>
  );
};

export default RegisterPage;
